apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helmrelease.yaml

namespace: production

commonLabels:
  app.kubernetes.io/environment: production
  app.kubernetes.io/part-of: super-todo

metadata:
  name: super-todo-production
