apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: super-todo
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/clusters/my-cluster/super-todo
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: super-todo
      namespace: default
  dependsOn:
    - name: flux-system
