apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: super-todo-production
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/environments/production
  prune: true
  targetNamespace: production
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: super-todo-production
      namespace: production
  dependsOn:
    - name: flux-system
