apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: super-todo-staging
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/environments/staging
  prune: true
  targetNamespace: staging
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: super-todo-staging
      namespace: staging
