apiVersion: v1
kind: Secret
metadata:
  name: {{ include "super-todo.fullname" . }}-secrets
  labels:
    {{- include "super-todo.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.secrets.databaseUrl | quote }}
  redis-url: {{ .Values.secrets.redisUrl | quote }}
