apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "super-todo.fullname" . }}
  labels:
    {{- include "super-todo.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
