apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "super-todo.fullname" . }}-config
  labels:
    {{- include "super-todo.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
    {{- if or (ne $key "DATABASE_URL") (not $.Values.database.useClusterSecret) }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
