apiVersion: v1
kind: Secret
metadata:
  name: super-todo-postgres-credentials
  labels:
    {{- include "super-todo.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: app
  password: changeme
  # Additional keys that CloudNativePG expects
  dbname: app
  host: super-todo-cnpg-cluster-rw
  port: "5432"
