apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helmrelease.yaml

namespace: default

commonLabels:
  app.kubernetes.io/name: super-todo
  app.kubernetes.io/part-of: super-todo

metadata:
  name: super-todo
  labels:
    app.kubernetes.io/name: super-todo
    app.kubernetes.io/part-of: super-todo
