apiVersion: v2
name: super-todo
description: A Helm chart for super-todo NestJS application
type: application
version: 0.7.9
appVersion: "0.0.1"
dependencies:
  - name: redis
    version: 18.0.0
    repository: https://charts.bitnami.com/bitnami
  - name: cluster
    version: 0.5.0
    repository: https://cloudnative-pg.github.io/charts
