apiVersion: v2
name: super-todo
description: A Helm chart for super-todo NestJS application
type: application
version: 0.7.7
appVersion: "0.0.1"
dependencies:
  - name: redis
    version: 18.0.0
    repository: https://charts.bitnami.com/bitnami
