apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

resources:
  - helmrepository.yaml
  - production/helmrelease.yaml
  - staging/helmrelease.yaml

# Ensure HelmRelease resources are applied before Cluster resources
patches:
  - target:
      kind: HelmRelease
    patch: |-
      - op: add
        path: /metadata/annotations/kustomize.config.k8s.io~1needs-hash
        value: "true"
