apiVersion: v2
name: super-todo
description: A Helm chart for deploying the super-todo NestJS application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - super-todo
  - nestjs
  - todo
maintainers:
  - name: DevOps Team
    email: devops@example.com
home: https://github.com/andreqko69/rd-course-project
sources:
  - https://github.com/andreqko69/rd-course-project
